name: AssistPl
version: '1.0'
main: me.hmPlugin.assistPl.AssistPl
api-version: '1.20'
commands:
  hm:
    description: Main command for the helper plugin
    usage: /hm <subcommand> [args...]
permissions:
  assistpl.nearby:
    description: Allows usage of the nearby command
    default: true